spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DATABASE_NAME}?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
  jwt:
    secret-key: ${JWT_SECRET_KEY}
  s3:
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    region: ${S3_REGION}
    bucket-name: ${S3_BUCKET_NAME}
  servlet:
    multipart:
      max-file-size: 5MB       # 개별 파일 크기 제한
      max-request-size: 20MB    # 전체 요청 크기 제한
  apple:
    grant-type: authorization_code
    client-id: ${APPLE_CLIENT_ID}
    key-id: ${APPLE_KEY_ID}
    team-id: ${APPLE_TEAM_ID}
    audience: https://appleid.apple.com
    private-key: ${APPLE_PRIVATE_KEY}
  kakao:
    admin-key: ${KAKAO_ADMIN_KEY}
logging:
  level:
    root: info