spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DATABASE_NAME}?serverTimezone=Asia/Seoul&cacheDefaultTimezone=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  jwt:
    secret-key: ${JWT_SECRET_KEY}
  s3:
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    region: ${S3_REGION}
    bucket-name: ${S3_BUCKET_NAME}
  servlet:
    multipart:
      max-file-size: 5MB       # 개별 파일 크기 제한
      max-request-size: 20MB    # 전체 요청 크기 제한
  apple:
    grant-type: authorization_code
    client-id: ${APPLE_CLIENT_ID}
    key-id: ${APPLE_KEY_ID}
    team-id: ${APPLE_TEAM_ID}
    audience: https://appleid.apple.com
    private-key: ${APPLE_PRIVATE_KEY}
  kakao:
    admin-key: ${KAKAO_ADMIN_KEY}
  discord:
    suggestion-webhook: ${DISCORD_SUGGESTION_WEBHOOK} # 개선 제안용 웹훅
    leave-webhook: ${DISCORD_LEAVE_WEBHOOK}           # 탈퇴 사유용 웹훅
    app-icon: ${APP_ICON}                             # 앱 아이콘
  admin:
    admin-email: ${ADMIN_EMAIL}
    admin-password: ${ADMIN_PASSWORD}
logging:
  level:
    root: info